name: Test, build and publish
on:
    push:
        branches:
            - main
        tags:
            - "*"
    pull_request:

env:
    DOCKER_HUB_USER: jenswbebot
    DOCKER_HUB_REPO: jenswbe/melthon
    PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

jobs:
    test:
        runs-on: ubuntu-latest
        outputs:
            docker_tag: ${{ steps.vars.outputs.docker_tag }}
        steps:
            - uses: actions/checkout@v2

            - name: Derive docker_tag
              id: vars
              shell: python
              run: |
                  import os
                  parts = os.environ["GITHUB_REF"].split("/")
                  tag = "".join(parts[2:]) # Skip first 2 parts
                  print(f"::set-output name=docker_tag::{tag}")

            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: "3.8"

            - name: Install dependencies
              run: |
                  python -m pip install -U pip wheel
                  pip install -r requirements.txt

            - name: Install melthon
              run: |
                  pip install .

            - name: Run unit tests
              run: |
                  python -m unittest

    build-and-publish-docker:
        needs: test
        runs-on: ubuntu-latest
        if: contains(github.ref, 'tags')
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ env.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: ${{ env.PLATFORMS }}
                  push: true
                  tags:
                      - ${{ env.DOCKER_HUB_REPO }}:latest
                      - ${{ env.DOCKER_HUB_REPO }}:${{ needs.test.outputs.docker_tag }}

            - name: Update repo description
              uses: peter-evans/dockerhub-description@v2
              with:
                  username: ${{ env.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
                  repository: ${{ env.DOCKER_HUB_REPO }}
